# Site settings
title: "Dev Journal"
email: theforecodingfeeling@gmail.com
description: "A deeper dive into my journey into code"
baseurl: ""
url: "http://theforecodingfeeling.github.io/"
title_description: "Just a teacher turned techie and aspiring web dev documenting her thoughts, frustrations, motivations and insights on this journey of self-taught discovery into the land of web development and programming. </br> </br> <em> Warning: If you're looking for tutorials only, this journal blog is not for you. While those will definitely be a part of this little project, this page is meant to be a look into my thought process a little beyond just the technical talk. </em> </br></br> Inspired by #100DaysOfCode"
title_image: "https://en.gravatar.com/userimage/166655706/613b8a865dbbb6cdb6cda07cdb00a78c.png?size=200"
disqus_account: 
github_repository: https://github.com/theforecodingfeeling
post_limit: 5

# Social usernames/URLs
twitter_username: theforecodingf1
github_username:  theforecodingfeeling
instagram_username: theforecodingfeeling

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using <a href=\"https://jekyllrb.com\"> Jekyll </a>"
footer_right: "&lt;/&gt; hosted on <a href=\"https://github.com/theforecodingfeeling\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
